// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Form = 2,
  True = 3,
  False = 4,
  Null = 5,
  Number = 6,
  String = 7,
  Object = 10,
  Property = 11,
  PropertyName = 12,
  Array = 15,
  Keyword = 16,
  Bool = 17
