// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {jsonHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bOYQPOOOOQO'#Cc'#CcOwQPO'#CfO!PQPO'#CkOOQO'#Cs'#CsQOQPOOOOQO'#Ch'#ChO!WQPO'#CgO!]QPO'#CuOOQO,59Q,59QO!eQPO,59QO!jQPO'#CxOOQO,59V,59VO!rQPO,59VOYQPO,59ROzQPO'#CnO!wQPO,59aOOQO1G.l1G.lOYQPO'#CoO#PQPO,59dOOQO1G.q1G.qOOQO1G.m1G.mOOQO,59Y,59YOOQO-E6l-E6lOOQO,59Z,59ZOOQO-E6m-E6m",
  stateData: "#X~OfOSPOS~ORSOSSOTSOUSOXQO^RO`SOaSOhPO~OWXOhUO~O][O~PYOj^O~Ok_OWiX~OWaO~OkbO]lX~O]dO~Ok_OWia~OkbO]la~O",
  goto: "!nmPPPPPPPnPPntzPPnPP!O!UPPP![P!hPP!kXSOR^bQWQRf_TVQ_Q`WRg`QcZRicQTOQZRQe^RhbRYQR]R",
  nodeNames: "⚠ Comment JsonText True False Null Number String } { Object Property PropertyName ] [ Array Keyword Bool",
  maxTerm: 28,
  nodeProps: [
    ["openedBy", 8,"{",13,"["],
    ["closedBy", 9,"}",14,"]"]
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "/[~RlXY!yYZ!y]^!ypq!yrs#Ost%h|}&S}!O&X!Q!R&b!R!['p![!](R!c!d(W!e!f(i!f!g)^!g!h*S!h!i*q!i!j+T!k!l,o!q!r,u!u!v,{!x!y+m!}#O-X#P#Q-^#Y#Z-c#b#c.Q#h#i.i#o#p/Q#q#r/V~#OOf~~#RWpq#Oqr#Ors#ks#O#O#O#P#p#P;'S#O;'S;=`%b<%lO#O~#pOh~~#sXrs#O!P!Q#O#O#P#O#U#V#O#Y#Z#O#b#c#O#f#g#O#h#i#O#i#j$`~$cR!Q![$l!c!i$l#T#Z$l~$oR!Q![$x!c!i$x#T#Z$x~${R!Q![%U!c!i%U#T#Z%U~%XR!Q![#O!c!i#O#T#Z#O~%eP;=`<%l#O~%mTP~OY%hZ]%h^;'S%h;'S;=`%|<%lO%h~&PP;=`<%l%h~&XOk~~&[Q!Q!R&b!R!['p~&gRU~!O!P&p!g!h'U#X#Y'U~&sP!Q![&v~&{RU~!Q![&v!g!h'U#X#Y'U~'XR{|'b}!O'b!Q!['h~'eP!Q!['h~'mPU~!Q!['h~'uSU~!O!P&p!Q!['p!g!h'U#X#Y'U~(WOj~~(ZP!p!q(^~(aP!f!g(d~(iOa~~(lP!t!u(o~(rP!g!h(u~(xP!c!d({~)OP!v!w)R~)UP!g!h)X~)^O`~~)aP!k!l)d~)gP!u!v)j~)mP!r!s)p~)sP!n!o)v~)yP!c!d)|~*PP!{!|)X~*VP!p!q*Y~*]P!f!g*`~*eSa~!e!f(i!h!i*q!i!j+T!x!y+m~*tP!q!r*w~*zP!t!u*}~+QP!o!p)X~+WP!k!l+Z~+^P!x!y+a~+dP!g!h+g~+jP!p!q)X~+pP!c!d+s~+vP!n!o+y~+|P!k!l,P~,SP!f!g,V~,YP!c!d,]~,`P!v!w,c~,fP!k!l,i~,lP!q!r+g~,rP!h!i(d~,xP!t!u(d~-OP!g!h-R~-UP!v!w)X~-^O^~~-cO]~~-fP#T#U-i~-lP#`#a-o~-rP#g#h-u~-xP#X#Y-{~.QOS~~.TP#i#j.W~.ZP#`#a.^~.aP#`#a.d~.iOT~~.lP#f#g.o~.rP#i#j.u~.xP#X#Y.{~/QOR~~/VOX~~/[OW~",
  tokenizers: [0],
  topRules: {"JsonText":[0,2]},
  tokenPrec: 0
})
